
import autoTable from "jspdf-autotable";
import jsPDF from "jspdf";
import { CircularProgressbar } from "react-circular-progressbar";
import "react-circular-progressbar/dist/styles.css";

import { useState, useRef } from "react";

function App() {
  const [file, setFile] = useState(null);
  const [jobDescription, setJobDescription] = useState("");
  const [analysis, setAnalysis] = useState(null);
  const [loading, setLoading] = useState(false);
  const [dragActive, setDragActive] = useState(false);
  const fileInputRef = useRef(null);

  const uploadResume = async () => {
    if (!file || !jobDescription) {
      alert("Please upload your resume");
      return;
    }

    const formData = new FormData();
    formData.append("file", file);
    formData.append("job_description", jobDescription);

    setLoading(true);

    try {
     const response = await fetch(
  "https://ai-resume-analyzer-4nb9.onrender.com/upload-resume",
  {
    method: "POST",
    body: formData,
  }
);
      

      const data = await response.json();

console.log("AI RESPONSE:", data.analysis);

const parsedAnalysis =
  typeof data.analysis === "string"
    ? JSON.parse(
        data.analysis
          .replace("```json", "")
          .replace("```", "")
          .trim()
      )
    : data.analysis;

setAnalysis(parsedAnalysis);



    } catch (error) {
      alert("Something went wrong");
      console.log(error);
    }

    setLoading(false);
  };
const handleDrag = (e) => {
  e.preventDefault();
  e.stopPropagation();

  if (e.type === "dragenter" || e.type === "dragover") {
    setDragActive(true);
  } else if (e.type === "dragleave") {
    setDragActive(false);
  }
};

const handleDrop = (e) => {
  e.preventDefault();
  e.stopPropagation();

  setDragActive(false);

  if (e.dataTransfer.files && e.dataTransfer.files[0]) {
    setFile(e.dataTransfer.files[0]);
  }
};
const downloadReport = () => {
  const doc = new jsPDF();
  console.log("PDF Analysis:", analysis);

  let y = 20;

  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;


  // Footer
  const addFooter = () => {
    doc.setFontSize(9);
    doc.setTextColor(120);

    doc.text(
      "Generated by AI Resume Analyzer",
      20,
      pageHeight - 10
    );

    doc.text(
      `Page ${doc.internal.getNumberOfPages()}`,
      pageWidth - 40,
      pageHeight - 10
    );
  };


  // Header
  doc.setFillColor(30, 64, 175);
  doc.rect(0, 0, pageWidth, 35, "F");


  doc.setTextColor(255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);

  doc.text(
    "AI Resume Analysis Report",
    20,
    20
  );


  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");

  doc.text(
    "Resume Intelligence & ATS Evaluation",
    20,
    29
  );


  y = 50;
  doc.setTextColor(0, 0, 0);

  doc.setFontSize(16);
doc.setFont("helvetica", "bold");
doc.text("Candidate Profile", 20, y);

y += 10;

doc.setFontSize(11);
doc.setFont("helvetica", "normal");

doc.text(
  `Name: ${(analysis["Candidate Name"] || "").trim()}`,
  20,
  y
);

y += 8;

doc.text(
  `Email: ${(analysis["Email"] || "").trim()}`,
  20,
  y
);

y += 8;

doc.text(
  `Phone: ${(analysis["Phone"] || "").trim()}`,
  20,
  y
);

y += 15;

  // ATS Score Box
  doc.setFillColor(220, 252, 231);
  doc.rect(
  20,
  y,
  170,
  35,
  "F"
);


  doc.setTextColor(22,101,52);
  doc.setFontSize(14);
  doc.setFont("helvetica","bold");

  doc.text(
    "ATS MATCH SCORE",
    30,
    y+12
  );


  doc.setFontSize(24);

  doc.text(
    `${analysis["ATS Match Score"]}/100`,
    30,
    y+27
  );


  y += 50;



  const addSection = (title, items) => {

    if (!items || items.length === 0)
      return;


    if (y > 250) {
      addFooter();
      doc.addPage();
      y = 20;
    }


    doc.setFontSize(14);
    doc.setFont("helvetica","bold");
    doc.setTextColor(30,64,175);

    doc.text(title,20,y);

    y += 8;


    doc.setFontSize(10);
    doc.setFont("helvetica","normal");
    doc.setTextColor(50);


    items.forEach((item)=>{

      const lines = doc.splitTextToSize(
        `• ${item}`,
        165
      );


      if(y + lines.length*6 > 280){
        addFooter();
        doc.addPage();
        y=20;
      }


      doc.text(
        lines,
        25,
        y
      );

      y += lines.length*6 + 3;

    });


    y += 8;

  };
  if (analysis["Resume Summary"]) {

  if (y > 250) {
    addFooter();
    doc.addPage();
    y = 20;
  }

  doc.setFontSize(14);
  doc.setFont("helvetica","bold");
  doc.setTextColor(30,64,175);

  doc.text(
    "Resume Summary",
    20,
    y
  );

  y += 8;

  doc.setFontSize(10);
  doc.setFont("helvetica","normal");
  doc.setTextColor(50);

  const summaryLines = doc.splitTextToSize(
    analysis["Resume Summary"],
    165
  );

  doc.text(
    summaryLines,
    20,
    y
  );

  y += summaryLines.length * 6 + 10;
}



  addSection(
    "Matching Skills",
    analysis["Matching Skills"]
  );


  addSection(
    "Missing Skills",
    analysis["Missing Keywords/Skills"]
  );


  addSection(
    "Strengths",
    analysis["Strengths"]
  );


  addSection(
    "Weaknesses",
    analysis["Weaknesses"]
  );


  addSection(
    "Recommended Technologies",
    analysis["Recommended Technologies"]
  );


  addSection(
    "Resume Improvement Suggestions",
    analysis["Resume Improvement Suggestions"]
  );
  // Interview Questions

if (analysis["Interview Questions"]) {

  addSection(
    "Technical Interview Questions",
    analysis["Interview Questions"]["Technical Questions"]
  );


  addSection(
    "HR Interview Questions",
    analysis["Interview Questions"]["HR Questions"]
  );


  addSection(
    "Project Interview Questions",
    analysis["Interview Questions"]["Project Questions"]
  );

}


  addFooter();


  doc.save(
    "AI_Resume_Analysis_Report.pdf"
  );
};

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-blue-900 to-slate-900 p-8">

      <div className="max-w-4xl mx-auto">

        
         <div className="text-center mb-10">
  <h1 className="text-5xl font-bold text-white">
    AI Resume Analyzer
  </h1>

  <p className="text-gray-300 mt-3 text-lg">
    Analyze your resume against any job description using AI
  </p>
</div>


        <div className="bg-white/10 backdrop-blur-lg rounded-3xl shadow-xl p-8 border border-white/20">

  <div
  onDragEnter={handleDrag}
  onDragOver={handleDrag}
  onDragLeave={handleDrag}
  onDrop={handleDrop}
  onClick={() => fileInputRef.current.click()}
  className={`border-2 border-dashed rounded-2xl p-10 text-center cursor-pointer transition-all
    ${dragActive
      ? "border-blue-500 bg-blue-50"
      : "border-gray-300 bg-gray-50"
    }`}
>
  <input
    ref={fileInputRef}
    type="file"
    accept=".pdf"
    onChange={(e) => setFile(e.target.files[0])}
    className="hidden"
  />

  <div className="text-5xl mb-4">📄</div>

  <p className="text-lg font-semibold">
    Drag & Drop your resume here
  </p>

  <p className="text-gray-500 mt-2">
    or click to browse files
  </p>

  {file && (
    <p className="mt-4 text-green-600 font-medium">
      Selected: {file.name}
    </p>
  )}
</div>

<textarea
  placeholder="Paste Job Description here..."
  value={jobDescription}
  onChange={(e) => setJobDescription(e.target.value)}
  className="border p-3 w-full mt-4 h-40"
/>
          <button
            onClick={uploadResume}
           className="mt-4 w-full bg-blue-600 hover:bg-blue-700 text-white py-3 rounded-xl font-semibold transition-all duration-300" 
          >
            {loading ? "🔍 Analyzing Resume..." : "Analyze Resume"}
          </button>

        </div>


        {analysis && (

          <div className="mt-8 space-y-6">
            <div className="bg-white rounded-3xl shadow-xl p-6 border border-gray-200">

  <h2 className="text-xl font-bold text-gray-700 mb-4">
    👤 Candidate Profile
  </h2>

  <div className="space-y-3 text-gray-700">

    <p>
      <span className="font-semibold">Name:</span>{" "}
      {analysis["Candidate Name"]}
    </p>

    <p>
      <span className="font-semibold">Email:</span>{" "}
      {analysis["Email"]}
    </p>

    <p>
      <span className="font-semibold">Phone:</span>{" "}
      {analysis["Phone"]}
    </p>

  </div>

</div>


            <div className="bg-white rounded-3xl shadow-2xl p-8 text-center border border-gray-200">

  <h2 className="text-xl font-semibold text-gray-600 uppercase tracking-wider">
    ATS Match Score
  </h2>

  <div className="mt-6">
   <div className="w-40 h-40 mx-auto mt-6">
  <CircularProgressbar
    value={analysis["ATS Match Score"]}
    text={`${analysis["ATS Match Score"]}%`}
  />
</div>
  

  <p className="mt-6 text-gray-600">
    Resume compatibility with the job description
  </p>

</div>
 </div>
 <div className="bg-white rounded-xl shadow p-6">

<h2 className="text-xl font-bold mb-4">
📄 Resume Summary
</h2>

<p className="text-gray-700 leading-relaxed">
{analysis["Resume Summary"]}
</p>

</div>


            <div className="bg-green-100 text-green-800 px-4 py-2 rounded-full font-medium">

              <h2 className="text-xl font-bold mb-3">
                Skills Found
              </h2>

              <div className="flex flex-wrap gap-2">

                {(analysis["Matching Skills"] || []).map(
                  (skill,index)=>(
                    <span
  key={index}
  className="bg-green-100 text-green-800 px-4 py-2 rounded-full font-medium shadow-sm hover:scale-105 transition"
>
  {skill}
</span>
                  )
                )}

              </div>

            </div>



            <div className="bg-white rounded-xl shadow p-6">

  <h2 className="text-xl font-bold mb-4">
    Missing Skills
  </h2>

  <div className="flex flex-wrap gap-3">

    {(analysis["Missing Keywords/Skills"] || []).map(
      (skill, index) => (
        <span
          key={index}
          className="bg-red-100 text-red-700 px-4 py-2 rounded-full font-medium shadow-sm hover:scale-105 transition"
        >
          {skill}
        </span>
      )
    )}

  </div>

</div>




<div className="bg-white rounded-xl shadow p-6">

  <h2 className="text-xl font-bold mb-4">
    💪 Strengths
  </h2>

  <div className="space-y-3">
    {(analysis["Strengths"] || []).map((item, index) => (
      <div
        key={index}
        className="bg-green-50 border border-green-200 rounded-xl p-4"
      >
        ✓ {item}
      </div>
    ))}
  </div>

</div>

<div className="bg-white rounded-xl shadow p-6">

  <h2 className="text-xl font-bold mb-4">
    ⚠️ Weaknesses
  </h2>

  <div className="space-y-3">
    {(analysis["Weaknesses"] || []).map((item, index) => (
      <div
        key={index}
        className="bg-red-50 border border-red-200 rounded-xl p-4"
      >
        {item}
      </div>
    ))}
  </div>

</div>

<div className="bg-white rounded-xl shadow p-6">

  <h2 className="text-xl font-bold mb-4">
    🚀 Recommended Technologies
  </h2>

  <div className="flex flex-wrap gap-3">

    {(analysis["Recommended Technologies"] || []).map(
      (tech, index) => (
        <span
          key={index}
          className="bg-blue-100 text-blue-700 px-4 py-2 rounded-full"
        >
          {tech}
        </span>
      )
    )}

  </div>

</div>
<div className="bg-white rounded-3xl shadow-xl p-6 border border-gray-200">

  <h2 className="text-xl font-bold text-gray-700 mb-5">
    🎤 Interview Preparation
  </h2>


  <h3 className="font-semibold text-blue-700 mb-2">
    Technical Questions
  </h3>

  <div className="space-y-3 mb-5">

    {(analysis["Interview Questions"]?.["Technical Questions"] || [])
      .map((question, index) => (

      <div
        key={index}
        className="bg-blue-50 p-3 rounded-xl border border-blue-200"
      >
        {index + 1}. {question}
      </div>

    ))}

  </div>


  <h3 className="font-semibold text-green-700 mb-2">
    HR Questions
  </h3>

  <div className="space-y-3 mb-5">

    {(analysis["Interview Questions"]?.["HR Questions"] || [])
      .map((question, index) => (

      <div
        key={index}
        className="bg-green-50 p-3 rounded-xl border border-green-200"
      >
        {index + 1}. {question}
      </div>

    ))}

  </div>


  <h3 className="font-semibold text-purple-700 mb-2">
    Project Questions
  </h3>

  <div className="space-y-3">

    {(analysis["Interview Questions"]?.["Project Questions"] || [])
      .map((question, index) => (

      <div
        key={index}
        className="bg-purple-50 p-3 rounded-xl border border-purple-200"
      >
        {index + 1}. {question}
      </div>

    ))}

  </div>


</div>

            <div className="bg-white rounded-xl shadow p-6">

              <h2 className="text-xl font-bold mb-3">
                Suggestions
              </h2>

              <div className="space-y-3">

 {analysis["Resume Improvement Suggestions"]?.map(
  (item, index) => (
    <div
      key={index}
      className="bg-gray-50 border border-gray-200 rounded-xl p-4 shadow-sm hover:shadow-md transition"
    >
      <span className="font-medium">✓</span> {item}
    </div>
  )
)}

</div>

<div className="text-center mt-8">
  <button
    onClick={downloadReport}
    className="bg-green-600 hover:bg-green-700 text-white px-8 py-3 rounded-xl font-semibold shadow-lg transition"
  >
    Download PDF Report
  </button>
</div>

            </div>


          </div>

        )}

      </div>

    </div>
  );
}

export default App;