import SplashScreen from "./SplashScreen";
import autoTable from "jspdf-autotable";
import jsPDF from "jspdf";
import Footer from "./components/Footer";
import { useState, useEffect, useRef } from "react";

import "react-circular-progressbar/dist/styles.css";
import {
  CircularProgressbar,
  buildStyles
} from "react-circular-progressbar";


function App() {


useEffect(() => {
  const timer = setTimeout(() => {
    setShowSplash(false);
  }, 2500);

  return () => clearTimeout(timer);
}, []);
  const [file, setFile] = useState(null);
  const [processing, setProcessing] = useState(false);
  const [jobDescription, setJobDescription] = useState("");
  const [analysis, setAnalysis] = useState(null);
  const [chatMessage, setChatMessage] = useState("");
const [chatHistory, setChatHistory] = useState([]);
const [chatLoading, setChatLoading] = useState(false);
  const [showSplash, setShowSplash] = useState(true);
const [loading, setLoading] = useState(false);
  const [loadingMessage, setLoadingMessage] = useState("");
  const [dragActive, setDragActive] = useState(false);

  const fileInputRef = useRef(null);

  const uploadResume = async () => {
    if (!file) {
      alert("Please upload your resume");
      return;
    }

    const formData = new FormData();
    formData.append("file", file);
    formData.append("job_description", jobDescription || "");

    setLoading(true);
    setProcessing(true);
    setLoadingMessage("Extracting resume content...");
setTimeout(() => {
  setLoadingMessage("Analyzing skills...");
}, 1500);

setTimeout(() => {
  setLoadingMessage("Calculating ATS score...");
}, 3000);

setTimeout(() => {
  setLoadingMessage("Generating interview questions...");
}, 4500);

setTimeout(() => {
  setLoadingMessage("Preparing final report...");
}, 6000);
    try {
      console.log("File:", file);
console.log("Job Description:", jobDescription);
     const response = await fetch(
  "https://ai-resume-analyzer-4nb9.onrender.com/upload-resume",
  {
    method: "POST",
    body: formData,
  }
);


console.log("Status:", response.status);


      const data = await response.json();

const parsedAnalysis =
  typeof data.analysis === "string"
    ? JSON.parse(
        data.analysis
          .replace("```json", "")
          .replace("```", "")
          .trim()
      )
    : data.analysis;

console.log("AI RESPONSE:", parsedAnalysis);
console.log("Available Keys:", Object.keys(parsedAnalysis));

console.log(
  "Interview Questions:",
  parsedAnalysis["Interview Questions"]
);

setAnalysis(parsedAnalysis);



    } catch (error) {
      alert("Something went wrong");
      console.log(error);
    }

    setLoading(false);
setProcessing(false);
setLoadingMessage("");
  };
const sendMessage = async () => {
  if (!chatMessage.trim()) return;

  const userMessage = chatMessage;

  setChatHistory((prev) => [
    ...prev,
    {
      role: "user",
      text: userMessage,
    },
  ]);

  setChatMessage("");
  setChatLoading(true);

  try {
    const response = await fetch(
      "https://ai-resume-analyzer-4nb9.onrender.com/chat",
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          message: userMessage,
        }),
      }
    );

    const data = await response.json();

    setChatHistory((prev) => [
      ...prev,
      {
        role: "user",
        text: userMessage,
      },
      {
        role: "bot",
        text: data.response,
      },
    ]);
  } catch (error) {
    console.log(error);
  }

  setChatLoading(false);
};

const handleDrag = (e) => {
  e.preventDefault();
  e.stopPropagation();

  if (e.type === "dragenter" || e.type === "dragover") {
    setDragActive(true);
  } else if (e.type === "dragleave") {
    setDragActive(false);
  }
};

const handleDrop = (e) => {
  e.preventDefault();
  e.stopPropagation();

  setDragActive(false);

  if (e.dataTransfer.files && e.dataTransfer.files[0]) {
    setFile(e.dataTransfer.files[0]);
  }
};
const downloadReport = () => {
  const doc = new jsPDF();
  console.log("PDF Analysis:", analysis);

  let y = 20;

  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;


  // Footer
  const addFooter = () => {
    doc.setFontSize(9);
    doc.setTextColor(120);

    doc.text(
      "Generated by AI Resume Analyzer",
      20,
      pageHeight - 10
    );

    doc.text(
      `Page ${doc.internal.getNumberOfPages()}`,
      pageWidth - 40,
      pageHeight - 10
    );
  };


  // Header
  doc.setFillColor(30, 64, 175);
  doc.rect(0, 0, pageWidth, 35, "F");


  doc.setTextColor(255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);

  doc.text(
    "AI Resume Analysis Report",
    20,
    20
  );


  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");

  doc.text(
    "Resume Intelligence & ATS Evaluation",
    20,
    29
  );


  y = 50;
  doc.setTextColor(0, 0, 0);

  doc.setFontSize(16);
doc.setFont("helvetica", "bold");
doc.text("Candidate Profile", 20, y);

y += 10;

doc.setFontSize(11);
doc.setFont("helvetica", "normal");

doc.text(
  `Name: ${(analysis["Candidate Name"] || "").trim()}`,
  20,
  y
);

y += 8;

doc.text(
  `Email: ${(analysis["Email"] || "").trim()}`,
  20,
  y
);

y += 8;

doc.text(
  `Phone: ${(analysis["Phone"] || "").trim()}`,
  20,
  y
);

y += 15;

  // ATS Score Box
  doc.setFillColor(220, 252, 231);
  doc.rect(
  20,
  y,
  170,
  35,
  "F"
);


  doc.setTextColor(22,101,52);
  doc.setFontSize(14);
  doc.setFont("helvetica","bold");

  doc.text(
    "ATS MATCH SCORE",
    30,
    y+12
  );


  doc.setFontSize(24);

  doc.text(
    `${analysis["ATS Match Score"]}/100`,
    30,
    y+27
  );


  y += 50;



  const addSection = (title, items) => {

    if (!items || items.length === 0)
      return;


    if (y > 250) {
      addFooter();
      doc.addPage();
      y = 20;
    }


    doc.setFontSize(14);
    doc.setFont("helvetica","bold");
    doc.setTextColor(30,64,175);

    doc.text(title,20,y);

    y += 8;


    doc.setFontSize(10);
    doc.setFont("helvetica","normal");
    doc.setTextColor(50);


    items.forEach((item)=>{

      const lines = doc.splitTextToSize(
        `• ${item}`,
        165
      );


      if(y + lines.length*6 > 280){
        addFooter();
        doc.addPage();
        y=20;
      }


      doc.text(
        lines,
        25,
        y
      );

      y += lines.length*6 + 3;

    });


    y += 8;

  };
  if (analysis["Resume Summary"]) {

  if (y > 250) {
    addFooter();
    doc.addPage();
    y = 20;
  }

  doc.setFontSize(14);
  doc.setFont("helvetica","bold");
  doc.setTextColor(30,64,175);

  doc.text(
    "Resume Summary",
    20,
    y
  );

  y += 8;

  doc.setFontSize(10);
  doc.setFont("helvetica","normal");
  doc.setTextColor(50);

  const summaryLines = doc.splitTextToSize(
    analysis["Resume Summary"],
    165
  );

  doc.text(
    summaryLines,
    20,
    y
  );

  y += summaryLines.length * 6 + 10;
}



  addSection(
    "Matching Skills",
    analysis["Matching Skills"]
  );


  addSection(
    "Missing Skills",
    analysis["Missing Keywords/Skills"]
  );


  addSection(
    "Strengths",
    analysis["Strengths"]
  );


  addSection(
    "Weaknesses",
    analysis["Weaknesses"]
  );


  addSection(
    "Recommended Technologies",
    analysis["Recommended Technologies"]
  );


  addSection(
    "Resume Improvement Suggestions",
    analysis["Resume Improvement Suggestions"]
  );
  
  // Interview Questions

if (analysis["Interview Questions"]) {

  addSection(
    "Technical Interview Questions",
    analysis["Interview Questions"]["Technical Questions"]
  );


  addSection(
    "HR Interview Questions",
    analysis["Interview Questions"]["HR Questions"]
  );


  addSection(
    "Project Interview Questions",
    analysis["Interview Questions"]["Project Questions"]
  );

}


  addFooter();


  doc.save(
    "AI_Resume_Analysis_Report.pdf"
  );
};
if (showSplash) {
  return <SplashScreen />;
}

if (processing) {
  return (
    <div className="
      h-screen
      flex
      flex-col
      justify-center
      items-center
      text-center
      bg-gradient-to-br
      from-slate-950
      via-blue-950
      to-black
      px-6
    ">

      <h1 className="text-4xl md:text-6xl font-bold text-white text-center">
        🧠 AI Analysis in Progress
      </h1>

      <p className="text-slate-400 mt-4 text-center">
        Processing your resume with advanced NLP models
      </p>

      <div className="w-[85%] max-w-md h-2 bg-white/10 rounded-full overflow-hidden mx-auto mt-8">
        <div className="progress-bar bg-gradient-to-r from-cyan-400 via-blue-500 to-purple-500 h-full"></div>
      </div>

      <div className="mt-10 w-full max-w-md space-y-4">

        <div className={`p-4 rounded-2xl backdrop-blur-xl border ${
          loadingMessage.includes("Extracting")
            ? "bg-cyan-500/20 border-cyan-400"
            : "bg-white/10 border-white/10"
        } text-white`}>
          📄 Extracting Resume Content
        </div>

        <div className={`p-4 rounded-2xl backdrop-blur-xl border ${
          loadingMessage.includes("skills")
            ? "bg-cyan-500/20 border-cyan-400"
            : "bg-white/10 border-white/10"
        } text-white`}>
          🔍 Analyzing Skills & Keywords
        </div>

        <div className={`p-4 rounded-2xl backdrop-blur-xl border ${
          loadingMessage.includes("ATS")
            ? "bg-cyan-500/20 border-cyan-400"
            : "bg-white/10 border-white/10"
        } text-white`}>
          📊 Calculating ATS Score
        </div>

        <div className={`p-4 rounded-2xl backdrop-blur-xl border ${
          loadingMessage.includes("Interview")
            ? "bg-cyan-500/20 border-cyan-400"
            : "bg-white/10 border-white/10"
        } text-white`}>
          💼 Generating Interview Questions
        </div>

        <p className="text-cyan-300 text-center animate-pulse mt-6">
          {loadingMessage}
        </p>

      </div>

    </div>
  );
}

if (loading) {
  return <SplashScreen />;
}

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-950 via-blue-950 to-slate-900">
 {!analysis && (
      <div className="max-w-4xl mx-auto">

        
         
<div className="text-center mb-10">
  <h1 className="text-5xl font-bold text-white">
    AI Resume Analyzer
  </h1>

  <p className="text-slate-300 mt-3 text-lg">
    Analyze your resume against any job description using AI
  </p>
</div>


        <div className="
bg-white/10
backdrop-blur-xl
border border-white/10
rounded-3xl
shadow-2xl
">

  <div
  onDragEnter={handleDrag}
  onDragOver={handleDrag}
  onDragLeave={handleDrag}
  onDrop={handleDrop}
  onClick={() => fileInputRef.current.click()}
  className={`border-2 border-dashed rounded-2xl p-10 text-center cursor-pointer transition-all
    ${dragActive
  ? "border-blue-400 bg-blue-500/20"
  : "border-white/20 bg-white/5"
}`}
>
  <input
    ref={fileInputRef}
    type="file"
    accept=".pdf"
    onChange={(e) => setFile(e.target.files[0])}
    className="hidden"
  />

  <div className="text-5xl mb-4">📄</div>

  <p className="text-lg font-semibold text-white">
    Drag & Drop your resume here
  </p>

  <p className="text-slate-400 mt-2">
    or click to browse files
  </p>

  {file && (
    <p className="mt-4 text-green-600 font-medium">
      Selected: {file.name}
    </p>
  )}
</div>

<textarea
  placeholder="Paste Job Description here (optional)"
  value={jobDescription}
  onChange={(e) => setJobDescription(e.target.value)}
  className="border border-white/20 bg-white/5 text-white placeholder-slate-400 p-4 w-full mt-4 h-40 rounded-2xl backdrop-blur-xl"
/>
          <button
            onClick={uploadResume}
           className="mt-4 w-full bg-blue-600 hover:bg-blue-700 hover:scale-[1.02] text-white py-3 rounded-xl font-semibold transition-all duration-300 shadow-lg hover:shadow-blue-500/30" 
          >
            {loading
  ? `🔍 ${loadingMessage}`
  : "Analyze Resume"}
          </button>

                </div>

      </div>
    )}

    {analysis && (
      <div className="max-w-4xl mx-auto mt-8">

          <div className="mt-8 space-y-6">
            <div className="bg-white/10 backdrop-blur-xl rounded-3xl shadow-2xl p-6 border border-white/10 text-white">
  <h2 className="text-xl font-bold text-slate-200 mb-4">
    👤 Candidate Profile
  </h2>

  <div className="space-y-3 text-slate-200">

    <p>
      <span className="font-semibold">Name:</span>{" "}
      {analysis["Candidate Name"]}
    </p>

    <p>
      <span className="font-semibold">Email:</span>{" "}
      {analysis["Email"]}
    </p>

    <p>
      <span className="font-semibold">Phone:</span>{" "}
      {analysis["Phone"]}
    </p>

  </div>

</div>


            <div className="bg-white/10 backdrop-blur-xl rounded-3xl shadow-2xl p-8 text-center border border-white/10 text-white">

  <h2 className="text-xl font-semibold text-slate-300 uppercase tracking-wider">
    ATS Match Score
  </h2>

  <div className="mt-6">
   <div className="w-40 h-40 mx-auto mt-6">
  <CircularProgressbar
  value={analysis["ATS Match Score"]}
  text={`${analysis["ATS Match Score"]}%`}
  styles={buildStyles({
    textColor:
      analysis["ATS Match Score"] >= 80
        ? "#4ade80"
        : analysis["ATS Match Score"] >= 50
        ? "#facc15"
        : "#ef4444",

    pathColor:
      analysis["ATS Match Score"] >= 80
        ? "#4ade80"
        : analysis["ATS Match Score"] >= 50
        ? "#facc15"
        : "#ef4444",

    trailColor: "#1e293b"
  })}
/>
</div>
  

  <p className="mt-6 text-slate-300">
    Resume compatibility with the job description
  </p>

</div>
 </div>
 <div className="bg-white/10 backdrop-blur-xl rounded-xl shadow-2xl p-6 border border-white/10 text-whit">

<h2 className="text-xl font-bold mb-4">
📄 Resume Summary
</h2>

<p className="text-slate-200 leading-relaxed">
{analysis["Resume Summary"]}
</p>

</div>


           <div className="bg-white/10 backdrop-blur-xl rounded-xl shadow-2xl p-6 border border-white/10 text-white">

              
               <h2 className="text-2xl font-bold text-white mb-4"> Skills Found
              </h2>

              <div className="flex flex-wrap gap-3 mt-4">

                {(analysis["Matching Skills"] || []).map(
                  (skill,index)=>(
                    <span
  key={index}
  className="bg-green-500/20
        text-green-300
        px-4
        py-2
        rounded-full
        font-medium
        border
        border-green-400/30
        shadow-sm
        hover:scale-105
        transition-all
        duration-300"
        >
  {skill}
</span>
                  )
                )}

              </div>

            </div>



            <div className="bg-white/10 backdrop-blur-xl rounded-xl shadow-2xl p-6 border border-white/10 text-whit">

  <h2 className="text-xl font-bold mb-4">
    Missing Skills
  </h2>

  <div className="flex flex-wrap gap-3">

    {(analysis["Missing Keywords/Skills"] || []).map(
      (skill, index) => (
        <span
          key={index}
          className="bg-red-100 text-red-700 px-4 py-2 rounded-full font-medium shadow-sm hover:scale-105 transition"
        >
          {skill}
        </span>
      )
    )}

  </div>

</div>




<div className="bg-white/10 backdrop-blur-xl rounded-xl shadow-2xl p-6 border border-white/10 text-whit">

  <h2 className="text-xl font-bold mb-4">
    💪 Strengths
  </h2>

  <div className="space-y-3">
    {(analysis["Strengths"] || []).map((item, index) => (
      <div
        key={index}
        className="bg-green-50 border border-green-200 rounded-xl p-4"
      >
        ✓ {item}
      </div>
    ))}
  </div>

</div>

<div className="bg-white/10 backdrop-blur-xl rounded-xl shadow-2xl p-6 border border-white/10 text-whit">

  <h2 className="text-xl font-bold mb-4">
    ⚠️ Weaknesses
  </h2>

  <div className="space-y-3">
    {(analysis["Weaknesses"] || []).map((item, index) => (
      <div
        key={index}
        className="bg-red-50 border border-red-200 rounded-xl p-4"
      >
        {item}
      </div>
    ))}
  </div>

</div>

<div className="bg-white/10 backdrop-blur-xl rounded-xl shadow-2xl p-6 border border-white/10 text-whit">

  <h2 className="text-xl font-bold mb-4">
    🚀 Recommended Technologies
  </h2>

  <div className="flex flex-wrap gap-3">

    {(analysis["Recommended Technologies"] || []).map(
      (tech, index) => (
        <span
          key={index}
          className="bg-blue-100 text-blue-700 px-4 py-2 rounded-full"
        >
          {tech}
        </span>
      )
    )}

  </div>

</div>
<div className="bg-white/10 backdrop-blur-xl rounded-3xl shadow-2xl p-6 border border-white/10 text-whit">

  <h2 className="text-xl font-bold text-slate-200 mb-5">
    🎤 Interview Preparation
  </h2>


  <h3 className="font-semibold text-blue-700 mb-2">
    Technical Questions
  </h3>

  <div className="space-y-3 mb-5">

    {(analysis["Interview Questions"]?.["Technical Questions"] || [])
      .map((question, index) => (

      <div
        key={index}
        className="bg-blue-50 p-3 rounded-xl border border-blue-200"
      >
        {index + 1}. {question}
      </div>

    ))}

  </div>


  <h3 className="font-semibold text-green-700 mb-2">
    HR Questions
  </h3>

  <div className="space-y-3 mb-5">

    {(analysis["Interview Questions"]?.["HR Questions"] || [])
      .map((question, index) => (

      <div
        key={index}
        className="bg-green-50 p-3 rounded-xl border border-green-200"
      >
        {index + 1}. {question}
      </div>

    ))}

  </div>


  <h3 className="font-semibold text-purple-700 mb-2">
    Project Questions
  </h3>

  <div className="space-y-3">

    {(analysis["Interview Questions"]?.["Project Questions"] || [])
      .map((question, index) => (

      <div
        key={index}
        className="bg-purple-50 p-3 rounded-xl border border-purple-200"
      >
        {index + 1}. {question}
      </div>

    ))}

  </div>


</div>

            <div className="bg-white/10 backdrop-blur-xl rounded-xl shadow-2xl p-6 border border-white/10 text-whit">

              <h2 className="text-xl font-bold mb-3">
                Suggestions
              </h2>

              <div className="space-y-3">

 {analysis["Resume Improvement Suggestions"]?.map(
  (item, index) => (
    <div
      key={index}
      className="bg-gray-50 border border-white/10 rounded-xl p-4 shadow-sm hover:shadow-md transition"
    >
      <span className="font-medium">✓</span> {item}
    </div>
  )
)}

</div>

<div className="text-center mt-8">
  <button
    onClick={downloadReport}
    className="bg-green-600 hover:bg-green-700 hover:scale-105 text-white px-8 py-3 rounded-xl font-semibold shadow-lg transition-all duration-300"
  >
    Download PDF Report
  </button>
</div>

            </div>

          </div>

      </div>
    )}
<div className="max-w-4xl mx-auto mt-10 bg-white/10 backdrop-blur-xl rounded-3xl p-6 border border-white/10 text-white">

  <h2 className="text-3xl font-bold mb-6">
    🤖 AI Assistant
  </h2>

  <div className="h-96 overflow-y-auto space-y-4 mb-6">

    {chatHistory.map((chat, index) => (

      <div key={index}>

        {chat.role === "user" ? (
          <div className="bg-blue-600 p-3 rounded-2xl ml-auto max-w-[80%]">
            {chat.text}
          </div>
        ) : (
          <div className="bg-white/10 p-3 rounded-2xl max-w-[80%]">
            {chat.text}
          </div>
        )}

      </div>

    ))}

    {chatLoading && (
      <p className="text-cyan-300 animate-pulse">
        AI is thinking...
      </p>
    )}

  </div>

  <div className="flex gap-3">

    <input
      value={chatMessage}
      onChange={(e) => setChatMessage(e.target.value)}
      placeholder="Ask anything..."
      className="flex-1 bg-white/10 border border-white/10 rounded-xl p-3 text-white"
    />

    <button
      onClick={sendMessage}
      className="bg-blue-600 px-6 rounded-xl hover:bg-blue-700"
    >
      Send
    </button>

  </div>

</div>
    <Footer />

  </div>
);
}

export default App;